auth_enabled: false

server:
  http_listen_port: 3100
  http_listen_address: 0.0.0.0

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  path_prefix: ${STORAGE_PATH:/loki}
  storage:
    filesystem:
      chunks_directory: ${STORAGE_PATH:/loki}/chunks
      rules_directory: ${STORAGE_PATH:/loki}/rules
  replication_factor: 1

schema_config:
  configs:
  - from: 2024-12-03
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

limits_config:
  allow_structured_metadata: true

ruler:
  alertmanager_url: http://localhost:9093

analytics:
  reporting_enabled: false